[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Lekton Nerd Font Mono"
# family = "Jetbrains Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.9
option_as_alt = "OnlyLeft"

# Colors (Everforest Dark)
# From https://github.com/alacritty/alacritty-theme

[colors.primary]
# background = '#232A2E'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

