[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Lekton Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

