source ~/.config/zsh/path.sh
source ~/.config/zsh/core.sh
# TODO: Make omz work properly with dotfiles git repo.
# Maybe add some symlink to local omz install, so that it is not present in the same directory?
source ~/.config/zsh/omz.sh
source ~/.config/zsh/variables.sh
source ~/.config/zsh/aliases.sh
source ~/.config/zsh/functions.sh
# TODO: add completions properly.
# source ~/.config/zsh/zellij-completions.sh

